/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { VERIFIER_ROUTER_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const RENOUNCE_OWNERSHIP_DISCRIMINATOR = new Uint8Array([
  19, 143, 91, 79, 34, 168, 174, 125,
]);

export function getRenounceOwnershipDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    RENOUNCE_OWNERSHIP_DISCRIMINATOR
  );
}

export type RenounceOwnershipInstruction<
  TProgram extends string = typeof VERIFIER_ROUTER_PROGRAM_ADDRESS,
  TAccountState extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountState extends string
        ? WritableAccount<TAccountState>
        : TAccountState,
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type RenounceOwnershipInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type RenounceOwnershipInstructionDataArgs = {};

export function getRenounceOwnershipInstructionDataEncoder(): FixedSizeEncoder<RenounceOwnershipInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: RENOUNCE_OWNERSHIP_DISCRIMINATOR })
  );
}

export function getRenounceOwnershipInstructionDataDecoder(): FixedSizeDecoder<RenounceOwnershipInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getRenounceOwnershipInstructionDataCodec(): FixedSizeCodec<
  RenounceOwnershipInstructionDataArgs,
  RenounceOwnershipInstructionData
> {
  return combineCodec(
    getRenounceOwnershipInstructionDataEncoder(),
    getRenounceOwnershipInstructionDataDecoder()
  );
}

export type RenounceOwnershipInput<
  TAccountState extends string = string,
  TAccountAuthority extends string = string,
> = {
  state: Address<TAccountState>;
  authority: TransactionSigner<TAccountAuthority>;
};

export function getRenounceOwnershipInstruction<
  TAccountState extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof VERIFIER_ROUTER_PROGRAM_ADDRESS,
>(
  input: RenounceOwnershipInput<TAccountState, TAccountAuthority>,
  config?: { programAddress?: TProgramAddress }
): RenounceOwnershipInstruction<
  TProgramAddress,
  TAccountState,
  TAccountAuthority
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? VERIFIER_ROUTER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    state: { value: input.state ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.state),
      getAccountMeta(accounts.authority),
    ],
    data: getRenounceOwnershipInstructionDataEncoder().encode({}),
    programAddress,
  } as RenounceOwnershipInstruction<
    TProgramAddress,
    TAccountState,
    TAccountAuthority
  >);
}

export type ParsedRenounceOwnershipInstruction<
  TProgram extends string = typeof VERIFIER_ROUTER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    state: TAccountMetas[0];
    authority: TAccountMetas[1];
  };
  data: RenounceOwnershipInstructionData;
};

export function parseRenounceOwnershipInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedRenounceOwnershipInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { state: getNextAccount(), authority: getNextAccount() },
    data: getRenounceOwnershipInstructionDataDecoder().decode(instruction.data),
  };
}
