[package]
name = "hello_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = {path = "/Users/hans/github.com/risc0/risc0/risc0/zkvm", default-features = false, features = ['std'] }
borsh = { version = "0.10.3" }
shared = { path = "../../../shared" }