[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
groth_16_verifier = "Hs9zHQshowrEM4tyRCv9vwcPkZSBbU1cVCUGLwZmVawa"
test_bad_verifier = "AdneDeXEyPk72VfLQMrQBTjuQj2fuBXm9efJdcB7eE3r"
verifier_router = "DNzgxRPwrWW7ZVTVWr5zhhHAJMjzs3B17eVpZVJfvzHa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
client = "yarn run ts-node scripts/codma.ts"
deploy = "yarn run ts-node scripts/deploy.ts"
estop = "yarn run ts-node scripts/estop.ts"
renounce = "yarn run ts-node scripts/renounceOwnership.ts"
transfer = "yarn run ts-node scripts/transferOwnership.ts"
add = "yarn run ts-node scripts/addVerifier.ts"
accept = "yarn run ts-node scripts/acceptOwnership.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = true
