[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
groth_16_verifier = "EsJUxZK9qexcHRXr1dVoxt2mUhVAyaoRWBaaRxH5zQJD"
test_bad_verifier = "H111vaTfs4ktTvJFqy46UFq5sjcEkixgmHwuHc6oabD8"
verifier_router = "8U8NcScoHfKhbJCCUCM4ckmynCbhFM9Mo2xLVgrbosfh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
accept = "yarn run ts-node scripts/acceptOwnership.ts"
add = "yarn run ts-node scripts/addVerifier.ts"
client = "yarn run ts-node scripts/codma.ts"
deploy = "yarn run ts-node scripts/deploy.ts"
estop = "yarn run ts-node scripts/estop.ts"
renounce = "yarn run ts-node scripts/renounceOwnership.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
transfer = "yarn run ts-node scripts/transferOwnership.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = true
