[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
groth_16_verifier = "BLRqPevHoJRbwNzB76PqmKURr2foFCrCVaMLtctMq5hH"
test_bad_verifier = "Ax2RSfhDcVo8wx8H9tEmqgHb69sGv9HHK1yueVmMK9bP"
verifier_router = "2NXuy9QcqgMMckYW7Jhb6Uxyyqb4PLqniwqowt2bwagK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
client = "yarn run ts-node scripts/codma.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = true
