[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
groth_16_verifier = "GwVHo4q6vcPVPiKzRHagxVCHF9GnfmnBwA2KSoKd3Ev1"
test_bad_verifier = "2wF5cbppQwdAEr13LUHzqnQ9tZ95YizhLtH65JkcZjnP"
verifier_router = "6QnGZ6qUAT5DnRLZPs8seCVfZkFnqtJQspqLnTfscnDM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
accept = "yarn run ts-node scripts/acceptOwnership.ts"
add = "yarn run ts-node scripts/addVerifier.ts"
client = "yarn run ts-node scripts/codma.ts"
deploy = "yarn run ts-node scripts/deploy.ts"
estop = "yarn run ts-node scripts/estop.ts"
renounce = "yarn run ts-node scripts/renounceOwnership.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
transfer = "yarn run ts-node scripts/transferOwnership.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = true
