[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
groth_16_verifier = "THq1qFYQoh7zgcjXoMXduDBqiZRCPeg3PvvMbrVQUge"
test_bad_verifier = "6UwNJdV4Q64iWHWrsTTonwhTFWTT3wg8RtzLX9fchp5W"
verifier_router = "6JvFfBrvCcWgANKh1Eae9xDq4RC6cfJuBcf71rp2k9Y7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
accept = "yarn run ts-node scripts/acceptOwnership.ts"
add = "yarn run ts-node scripts/addVerifier.ts"
client = "yarn run ts-node scripts/codma.ts"
deploy = "yarn run ts-node scripts/deploy.ts"
estop = "yarn run ts-node scripts/estop.ts"
renounce = "yarn run ts-node scripts/renounceOwnership.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
transfer = "yarn run ts-node scripts/transferOwnership.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = true
