name: tests

on:
  push:
    branches: [ main ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RUST_BACKTRACE: "1"

jobs:
  rust-tests:
    runs-on: [ self-hosted, prod, "${{ matrix.os }}", "${{ matrix.arch }}", "${{ matrix.device }}" ]
    strategy:
      matrix:
        include:
          - os: Linux
            arch: X64
            feature: default
            device: cpu
    steps:
      - name: clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: install rust
        uses: risc0/risc0/.github/actions/rustup@main

      - name: solana-verifier Cargo tests
        working-directory: ./solana-verifier
        run: cargo test --locked

  anchor-tests:
    runs-on: [ self-hosted, prod, "${{ matrix.os }}", "${{ matrix.arch }}", "${{ matrix.device }}" ]
    strategy:
      matrix:
        include:
          - os: Linux
            arch: X64
            feature: default
            device: cpu
    steps:
      - name: clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: install rust
        uses: risc0/risc0/.github/actions/rustup@main

      - name: Install Solana CLI
        run: sh -c "$(curl -sSfL https://release.solana.com/v1.10.32/install)"

      - name: Install Anchor CLI
        run: cargo install --git https://github.com/coral-xyz/anchor anchor-cli --tag v0.31.1

      - name: Build and Test
        run: anchor test
